server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: content-management
          uri: lb://content-management
          predicates:
          - Path=/api/v1/content
        - id: user-management
          uri: lb://usermanagement
          predicates:
            - Path=/api/v1/auth/register

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

