server:
  port: 8080

jwt:
  publicKey: todoPublicKey

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: content-management
          uri: lb://content-management
          predicates:
            - Path=/api/v1/content/**
          filters:
            - JwtAuthenticationFilter
        - id: user-management
          uri: lb://user-management
          predicates:
            - Path=/api/v1/auth/register,/api/v1/auth/authenticate,/api/v1/auth/refresh,/api/v1/user,/api/v1/user/{username}
          filters:
            - JwtAuthenticationFilter
        - id:  scraping-service
          uri: lb://scraping-service
          predicates:
            - Path=/api/v1/scraper
        - id: podcast-service
          uri: lb://podcast-service
          predicates:
            - Path=/podcast/**
        - id: streaming-service
          uri: lb://streaming-service
          predicates:
            - Path=/api/v1/stream

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
