server:
  port: 8080

jwt:
  publicKey: todoPublicKey

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
        - id: content-management
          uri: lb://content-management
          predicates:
            - Path=/api/v1/content
          filters:
            - JwtAuthenticationFilter
        - id: user-management
          uri: lb://usermanagement
          predicates:
            - Path=/api/v1/auth/register
          filters:
            - JwtAuthenticationFilter

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

