server:
  port: 8082

spring:
  application:
    name: content-management
  datasource:
    url: jdbc:postgresql://localhost:5432/audiophile
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

config:
  streaming:
    urlPrefix: http://localhost:8080/api/v1/stream?url=
