server:
  port: 0

spring:
  application:
    name: podcast-feed-generator

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

config:
  streaming:
    urlPrefix: http://localhost:8080/api/v1/stream?url=
