server:
  port: 8081

spring:
  application:
    name: scraping-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


config:
  youtubedl:
    path: yt-dlp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
